import type { Metadata } from "next";
import { LegalPage, Section } from "@/components/Legal";

export const metadata: Metadata = {
  title: "User Generated Content Policy — DidntHappen",
  description: "Rules and rights for content you create or share through DidntHappen.",
};

export default function UgcPage() {
  return (
    <LegalPage title="User Generated Content Policy">
      <Section title="1. What counts as user content">
        Any text, voice transcript, share card, profile field, or other material you create through DidntHappen. Most of your content is private by default and stays in your account.
      </Section>
      <Section title="2. Your rights and licence">
        You keep ownership of everything you create. By using DidntHappen you grant us a limited, non-exclusive, royalty-free, worldwide licence to host, store, process, display, and transmit your content solely to operate the app for you. We do not use your content to train external AI models or sell it to third parties.
      </Section>
      <Section title="3. Your responsibility">
        You are solely responsible for the content you submit. You confirm that you own it or have the rights to share it, and that it does not violate any law, the Acceptable Use Policy, or the rights of any third party.
      </Section>
      <Section title="4. Removal and takedown">
        We may remove or disable access to content that, in our judgement, violates this policy, the Acceptable Use Policy, or applicable law. We may notify you before removal unless we believe the content presents immediate harm. You can request removal of your own content at any time from Settings or by emailing <a href="mailto:abuse@didnthappen.app">abuse@didnthappen.app</a>.
      </Section>
      <Section title="5. Share cards">
        When you tap Share inside the app, a card is generated locally with your stats or progress text. Sharing the card publicly is your choice. Once shared outside the app, the recipient platform's rules apply.
      </Section>
      <Section title="6. Mira outputs">
        Mira's responses are generated by AI based on your input. You may use them for personal reflection. You may not pass them off as professional advice or as content authored by a person.
      </Section>
      <Section title="7. Reporting">
        Report user content concerns to <a href="mailto:abuse@didnthappen.app">abuse@didnthappen.app</a> or via <a href="/abuse">/abuse</a>. Copyright complaints go to <a href="mailto:copyright@didnthappen.app">copyright@didnthappen.app</a>.
      </Section>
    </LegalPage>
  );
}
